### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/learn-heroku#11]
Hey @nelsonic I've been making my way through the tutorial for setting up an SSL certificate but I keep running into an error with TLS: 
<img width="567" alt="screen shot 2017-08-23 at 20 27 57" src="https://user-images.githubusercontent.com/12450298/29634794-e69833a8-8842-11e7-888b-63e48b5035fa.png">

I've been googling around but can't seem to find anything that's helpful for my use-case.

Did you experience this error at all?

**Comment by nelsonic** [comment]
@jackcarlisle when you visit http://jumpstartjs.com/ what do you _expect_ to see?
(_trying to confirm if the DNS has been properly configured to point to Heroku...?_)

**Comment by jackcarlisle** [comment]
@nelsonic so it should forward to http://www.jumpstartjs.com which points to jumpstartjs.com.herokudns.com 

Here's my DNS config:

<img width="1000" alt="screen shot 2017-08-24 at 09 01 15" src="https://user-images.githubusercontent.com/12450298/29656015-dc288ba8-88aa-11e7-93a8-71f0ade27884.png">

Currently if I visit http://jumpstartjs.com it forwards to https://www.jumpstartjs.com : 

<img width="571" alt="screen shot 2017-08-24 at 09 05 33" src="https://user-images.githubusercontent.com/12450298/29656160-702472c2-88ab-11e7-9788-47190ce20b18.png">

If I go to just www.jumpstartjs.com I see this:

![screen shot 2017-08-24 at 09 07 06](https://user-images.githubusercontent.com/12450298/29656213-b26a23fc-88ab-11e7-9aea-aae3ffb1585d.png)
 
because I'm still deploying the `letsencrypt-temporary-server` branch.

**Comment by nelsonic** [comment]
@jackcarlisle so far so good. 👍 
When you visit the url for the `.well-known/acme-challenge/...etc` does it download a file?
also, is your plan to use the `www.` subdomain as your main URL?

**Comment by jackcarlisle** [comment]
@nelsonic it doesn't automatically download a file but if I click on one of the blue links it does. It just shows this page:
<img width="843" alt="screen shot 2017-08-25 at 11 20 38" src="https://user-images.githubusercontent.com/12450298/29710314-a40bff10-8987-11e7-8e8c-54c4259e56a2.png">

And yes the plan is to use www. as the main one

**Comment by jackcarlisle** [comment]
@nelsonic I've re-run certbot but I'm still experiencing this TLS error, any idea for what might be causing it?

**Comment by jackcarlisle** [comment]
I re-ran it *again* and it gave me a different error this time:

<img width="567" alt="screen shot 2017-09-14 at 12 06 21" src="https://user-images.githubusercontent.com/12450298/30426792-3f98b032-9945-11e7-9c78-4a0414fbb797.png">

It keeps asking me to create two files in `.well-known/acme-challenge`. Am I doing something wrong @nelsonic ?

When I visit https://www.jumpstartjs.com/.well-known/acme-challenge/9ChX8PerOn21OR_ARdyXUFhjj-TTbgnxp3NlsfASGYc it says that this site can't provide a secure connection. It might be something to do with my DNS but I'm not sure where to start. When I visit the `http` version of the url it downloads the file as expected.

**Comment by jackcarlisle** [comment]
### Solution

In my DNS settings I was forwarding my requests to the https version of the site when I should have been using the http version. Now that SSL is set up I can swap it back

**Comment by nelsonic** [comment]
@jackcarlisle thanks for sharing the solution. 🎉 
if this is no longer an issue for you, please close. 👍 
Hope your summer is going well. ☀️

**Comment by nelsonic** [comment]
Closing as resolved. ✅
