### ISSUE TITLE
Heroku App Crashed 503 status=503

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-heroku#12]
Error:
```
2017-10-03T08:04:59.568303+00:00 heroku[router]: at=error code=H10 
desc="App crashed" method=GET path="/favicon.ico" 
host=github-oauth-demo.herokuapp.com 
request_id=6deb46cc-e65d-4450-8582-dc9f4ce6142d fwd="46.28.161.222" 
dyno= connect= service= status=503 bytes= protocol=https
```
![image](https://user-images.githubusercontent.com/194400/31115441-a9b2b8aa-a822-11e7-89df-5778b76a4b0d.png)

This is happening for: https://github.com/nelsonic/github-oauth-demo
should be an easy fix.

**Comment by nelsonic** [comment]
ah... ok, I've figured it out. major PEBKAC...!
I've not included the _necessary_ dependencies (_they are in `devDependencies`_...)

**Comment by Bijou-LM** [comment]
You need to change the Icon that you edited in angular.json 
"assets": [
              "src/favicon.ico",
              "src/assets"
            ],

hit favicon.ico instaed of what you found .Should work now
