### ISSUE TITLE
Heroku in production with node.js?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-heroku#14]
I'm working on a project at the moment where we are deploying to heroku (free tier at the moment for development) and I'm confused by what will be needed in terms of dynos when it comes to deploying the app for production. 

How many concurrent users are _too many_ when using a hobby dyno? This app is likely to have a reasonably low amount of regular concurrent users and from a bit of reading I wouldn't need to look into the professional tiers unless I would be looking at more than 100 concurrent users?

How do you decide whether your app will be okay on hobby, or if it needs professional? 

I think something around this kind of info would be great to have in this README, so if we manage to collate some answers here I'd be happy to make a PR with them.

**Comment by nelsonic** [comment]
@ZooeyMiller keep an eye out for the heroku alerts as they will tell you when you are running out of capacity (_or over capacity_). we run several production apps on Heroku and the bills are around $20/month we only need/use "professional" on _one_ of the apps and that's around $200/month which is still cheaper than migrating the data to AWS and maintaining the "instances". 
Most people don't realise that the most "expensive" thing about heroku is data storage. 💸 

> Conclusion: Use one Hobby Dyno and monitor the logs (_get an email when it hits 80% capacity_)
> Investigate autoscaling: https://blog.heroku.com/heroku-autoscaling

**Comment by nelsonic** [comment]
There are _many_ other options for `Node.js` apps in 2024 e.g: https://fly.io/docs/js
Closing. ✅
