### ISSUE TITLE
Markdown formatting error

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-heroku#15]
There's one section in the readme where an intended H4 renders with 4 `#`s in front of it, rather than as a header. 

![screenshot from 2017-11-22 10-20-21](https://user-images.githubusercontent.com/21139983/33116837-f14efe9e-cf6e-11e7-9261-9d3645491c08.png)

**Comment by nelsonic** [comment]
need to figure out why my Atom Editor keeps "breaking" the markdown formatting by introducing the irregular space character. 🙄 
@ZooeyMiller please fix if you can. 👍

**Comment by nelsonic** [comment]
Fixed at the time. Closing. ✅
