### ISSUE TITLE
Heroku build pack or Docker file?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-heroku#2]
What is an Heroku Build pack and how can I use it to deploy my app?

**Comment by gabrielperales** [comment]
why use a build pack if you can use docker containers on heroku?

**Comment by nelsonic** [comment]
@gabrielperales a Docker container is good idea for heroku. 
right now I'm trying to keep this tutorial as beginner-friendly as possible but in the "_advanced_" section we can definitely cover Docker! 👍

**Comment by nelsonic** [comment]
Looking into this now.
https://devcenter.heroku.com/articles/buildpacks#

**Comment by nelsonic** [comment]
started looking into it ... think its a good idea but not "MVP" so just going to deploy _manually_ for now. see: https://github.com/nelsonic/time-mvp/issues/3#issuecomment-298219528

**Comment by nelsonic** [comment]
Spoiler: `Dockerfile` won. 🐳 ✅
