### ISSUE TITLE
Join buildpack sections

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-heroku#23]
In https://github.com/dwyl/learn-heroku/blob/master/elixir-phoenix-app-deployment.md the section 5 could be next to the section 9 and more information about the buildpacks configuration can be added:

![image](https://user-images.githubusercontent.com/6057298/36486950-a9ee8d8a-1717-11e8-9721-abb5587621de.png)
 
and

![image](https://user-images.githubusercontent.com/6057298/36486979-c000e26c-1717-11e8-9e31-f94eb1d09424.png)

see: https://github.com/dwyl/learn-heroku/pull/18#pullrequestreview-98185047

**Comment by nelsonic** [comment]
@SimonLab agreed.
But what we _could_ consider is removing section 5 _entirely_ because we aren't actually _customising_ anything in the buildpack ... 🤔

**Comment by nelsonic** [comment]
Done. ✅
