### ISSUE TITLE
"Cross-link" to learn-ngrok for people who just want to ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-heroku#24]
Should we "cross-link" to the https://github.com/dwyl/learn-ngrok tutorial 
for people who "_just_" want show their app in a Demo without _deploying_ it?
The _obvious_ advantage is that changes can be made (_with "live-reloading"_) on `ngrok`
without having to go through the "_minutes_" of re-deploying to Heroku.

@iteles thoughts?

**Comment by papamarfo** [comment]
I think adding a "cross-link" will be a good idea but do we do it for all Heroku alternatives as well?

@nelsonic

**Comment by nelsonic** [comment]
@manfordbenjamin good question.
The cross link is just to let people know that if their goal 
is simply to show the App running on their `localhost` 
and not _need_ to deploy to any service.

as for Heroku alternatives, which ones are you familiar with?

**Comment by papamarfo** [comment]
Alternatives include AWS and Google Cloud. Not sure if there are tutorials that cover those topics aside Heroku.

**Comment by nelsonic** [comment]
@manfordbenjamin 👍 
our AWS tutorial https://github.com/dwyl/learn-amazon-web-services isn't up-to-date
and we don't (_yet_) have a _beginners_ tutorial for Google Cloud that shows deploying a basic app. 
Have you had a chance to deploy to either of these?

**Comment by papamarfo** [comment]
Awesome. I have a little experience with AWS but i can give Google services a try.

**Comment by papamarfo** [comment]
@nelsonic  Any update on this?? Are we doing the cross linking or we should leave both tuts separate??

**Comment by iteles** [comment]
@manfordbenjamin We should definitely still do the original cross-link from the OP (for ngrok) but the others will have to wait until we have tutorials for them :)

**Comment by nelsonic** [comment]
Closing as we are no longer using Heroku. #52
