### ISSUE TITLE
Heroku vs AWS

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-heroku#3]
https://medium.com/@aleicher/should-i-use-heroku-or-aws-3bfcd4706a36
snapshot pdf: [Should I use Heroku or AWS.pdf](https://github.com/dwyl/learn-heroku/files/793490/Should.I.use.Heroku.or.AWS_.Medium.pdf)

**Comment by gabrielperales** [comment]
what about Heroku vs [now.sh](https://zeit.co/now) it also has a free plan and it is amazing easy to use. Works with nodejs and docker!

**Comment by nelsonic** [comment]
We don't use `Heroku` anymore so closing this. ✅
